# Generated by Django 5.2b1 on 2025-05-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_clicks_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=20)),
                ("resolution", models.CharField(max_length=20)),
                ("quality", models.CharField(max_length=20)),
                ("note", models.CharField(max_length=1000)),
                ("prompt", models.CharField(max_length=5000)),
                ("img_path", models.CharField(max_length=200)),
                ("sessionid", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("processed", models.IntegerField(default=0)),
                ("imgen_result", models.CharField(default="", max_length=3000)),
                ("time_used", models.FloatField(default=0)),
                ("word", models.CharField(default="", max_length=100)),
                ("prompt_meta", models.CharField(default="", max_length=3000)),
            ],
        ),
    ]
