# Generated by Django 5.2b1 on 2025-05-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_prompts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompts",
            name="prompt_meta",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
