# Generated by Django 5.2b1 on 2025-05-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_prompts_prompt_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompts",
            name="inqueue",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="prompts",
            name="prompt_meta",
            field=models.CharField(default="", max_length=3000),
        ),
    ]
