# Generated by Django 5.2b1 on 2025-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_prompts_inqueue_alter_prompts_prompt_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompts",
            name="prompt_meta_hash",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
