# Generated by Django 5.2b1 on 2025-03-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessstatistic",
            name="ip_address",
            field=models.CharField(default="Unknown", max_length=30),
        ),
        migrations.AddField(
            model_name="accessstatistic",
            name="url_visited",
            field=models.CharField(default="Unknown ", max_length=200),
        ),
    ]
