# Generated by Django 5.2b1 on 2025-03-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_accessstatistic_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessstatistic",
            name="user",
            field=models.CharField(default="Unknown", max_length=30),
        ),
    ]
