# Generated by Django 5.2b1 on 2025-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_accessstatistic_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessstatistic",
            name="browser_info",
            field=models.CharField(default="Unknown ", max_length=200),
        ),
        migrations.AddField(
            model_name="accessstatistic",
            name="is_robot",
            field=models.BooleanField(default=False),
        ),
    ]
