# Generated by Django 5.2b1 on 2025-03-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_accessstatistic_browser_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessstatistic",
            name="owner",
            field=models.CharField(default="Unknown", max_length=200),
        ),
    ]
