# Generated by Django 5.2b1 on 2025-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_accessstatistic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessstatistic",
            name="detail_ipinfo",
            field=models.CharField(default="Unknown", max_length=2048),
        ),
    ]
