# Generated by Django 5.0.10 on 2025-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
